// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5vDZ5XiQ9MKdVWyMWSprFdu1dTKGonzo',
    appId: '1:516818658780:android:48e63b5aa28eea818c1b19',
    messagingSenderId: '516818658780',
    projectId: 'friend-lms-01',
    storageBucket: 'friend-lms-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRr_zFtnIBF0z1t9lT9DO4L4vFGkbRmq4',
    appId: '1:516818658780:ios:9922f813dcae36ff8c1b19',
    messagingSenderId: '516818658780',
    projectId: 'friend-lms-01',
    storageBucket: 'friend-lms-01.firebasestorage.app',
    iosBundleId: 'com.example.lms',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWQVECU0P0LfYHVssageCg2Icn1ZRTxo0',
    appId: '1:516818658780:web:5b8a31c5471b1ca38c1b19',
    messagingSenderId: '516818658780',
    projectId: 'friend-lms-01',
    authDomain: 'friend-lms-01.firebaseapp.com',
    storageBucket: 'friend-lms-01.firebasestorage.app',
  );

}